services:
  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: express-app
    container_name: watchtower

  express-app:
    image: kmz122/express-app
    ports:
      - 8080:8080
    container_name: express-app
